name: OCI ARM Instance Creator
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  create-arm-instance:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_USER_ID }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_ID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_PRIVATE_KEY }}
      OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
    steps:
      - name: Install OCI CLI
        run: pip install oci-cli
      - name: Try Create ARM Instance
        run: |
          oci compute instance launch \
            --compartment-id "${{ secrets.OCI_TENANCY_ID }}" \
            --shape "VM.Standard.A1.Flex" \
            --shape-config '{"ocpus":4,"memoryInGBs":24}' \
            --image-id "${{ secrets.OCI_IMAGE_ID }}" \
            --subnet-id "${{ secrets.OCI_SUBNET_ID }}" \
            --display-name "arm-auto" \
            --ssh-authorized-keys-file <(echo "${{ secrets.OCI_SSH_PUBLIC_KEY }}") \
            --assign-public-ip true \
            --wait-for-state RUNNING || true
